# fly.toml app configuration file generated for re-mem-ber on 2023-05-27T16:30:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "re-mem-ber"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[[mounts]]
  source = "remember_vol"
  destination = "/mnt/remember_vol"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

